common_params:
  gpu: "0,1,2,3"
  seed: 1
  experiment_id: "20260321"
  checkpoint: null
  pretrained_model: null


save_params:
  save_path: "/mnt/home/chensitao/code/DRVR/experiments/DRVR-Occ3D/"
  save_file: 
    - "/mnt/home/chensitao/code/DRVR/config/drvr_occ3d.yaml"
    - "/mnt/home/chensitao/code/DRVR/dataloader/dataset_nus_occ3d.py"
    - "/mnt/home/chensitao/code/DRVR/models/*.py"
    - "/mnt/home/chensitao/code/DRVR/tasks/nuscenes_occ3d/*.py"


model_params:
  net_type: "DRVR"
  query_shape: [100, 100, 8]
  num_classes: 18
  cross_attn_embed_dims: 128
  cross_attn_ffn_dims: 512
  cross_attn_n_heads: 4
  cross_attn_n_points: 8
  cross_attn_n_levels_1_2: 1
  cross_attn_n_layers_1_2: 3
  spatial_shape_list: [[100,100,16], [50,50,8], [25,25,4]]
  height_maxpool_list: [4, 4, 4]
  pretrained_model: "/mnt/home/chensitao/code/DRVR/pretrained/CENet_nuScenes.pth"


dataset_params:
  dataset_name: "nus_occ3d"
  data_path: "/mnt/dataset/nuscenes/"
  label_path: "/mnt/dataset/Occ3D_nuScenes/trainval/"
  anno_path: "/mnt/dataset/Occ3D_nuScenes/trainval/annotations.json"
  mask_camera: False # True
  grid_shape_list: [[100,100,16], [50,50,8], [25,25,4]]
  max_volume_space: [40, 40, 5.4]
  min_volume_space: [-40, -40, -1]
  proj_img_size: [64, 2048]
  range_img_means: [12.12, 10.88, 0.23, -1.04, 0.21]
  range_img_stds: [12.32, 11.47, 6.91, 0.86, 0.16]
  fov_up: 10
  fov_down: -30
  coarse_cls_freq: [19918, 4473]
  fine_cls_freq: [1892500630, 3012896, 234043, 5385264, 34145527, 2044061, 
                  325758, 3330189, 543801, 5784830, 13520735, 175883646, 
                  4275424, 51393615, 61411620, 227783782, 252350317, 2082256]

  train_data_loader:
    batch_size: 1
    num_workers: 4   
    flip_aug: True
    
  val_data_loader:
    batch_size: 1
    num_workers: 4
    flip_aug: False


train_params:
  max_num_epochs: 50
  report_epochs: 1
  warmup_epochs: 1
  learning_rate: 0.001
  lr_momentum: 0.9
  optimizer: AdamW  # [SGD, Adam, AdamW]
  momentum: 0.9
  nesterov: True
  weight_decay: 0.01  # SGD:1.0e-4, Adam/AdamW:0.01
  focal_weight: 1.0
  dice_weight: 1.0


infer_params:
  model_path: null
  save_dir: null
  save_pred: False # True